### ISSUE TITLE
Suggesting for an option to change x/y offset of the GUI

### ISSUE THREAD

**Issue by Scarlaid** [intact/arrows-info#1]
![image](https://user-images.githubusercontent.com/90851437/166431251-76ed33e9-7f6c-4135-a495-8a4ddc3e238d.png)
The context is the image

**Comment by intact** [comment]
Do resource pack move hot bar or some mod do that?

edit: Looks like [armor-hud](https://github.com/BerdinskiyBear/armor-hud) mod is used but something else is moving hotbar.

**Comment by Scarlaid** [comment]
The mod is [Raised](https://www.curseforge.com/minecraft/mc-mods/raised)

**Comment by intact** [comment]
Problem is fixed in new Arrows Info and Raised mods releases.

**Comment by yurisuika** [comment]
Hey, just letting you know that I've refactored stuff in version 1.2.0. `distance` is now `hud` and `offset` is now `chat`.

**Comment by intact** [comment]
> Hey, just letting you know that I've refactored stuff in version 1.2.0. `distance` is now `hud` and `offset` is now `chat`.

Thanks for info :)
