### ISSUE TITLE
[Compatability] Raised

### ISSUE THREAD

**Issue by BeastSlayer666** [intact/arrows-info#7]
I've noticed while using this mod with Raised that the arrows slot is unaligned with the hotbar.

![image](https://github.com/intact/arrows-info/assets/87861236/1ee74644-7aef-4ba3-adbd-880243ea0117)

**Comment by intact** [comment]
Minecraft's and Raised versions?

You can try to disable Share in Raised's options.

**Comment by BeastSlayer666** [comment]
Disabling share fixes the issue:)

I feel a little silly for not being more thorough before posting an issue. 

Thanks a bunch for your help!
